### ISSUE TITLE
Initial Code Request Feature

### ISSUE THREAD

**Issue by cdaniel42** [andreasdoerr/impf_termin_tester#17]
@bastian987 @andreasdoerr I am working on an extension to receive the initial Code, just as Information In case one of you is doing the same to avoid double work ^^.

**Comment by bastian987** [comment]
Yep, started to discuss it with Andreas already ;) Let me know if I can support.

**Comment by cdaniel42** [comment]
One question is how to integrate it. Currently I am inheriting from 'Browser' and have a sub-class for the new feature. I am not sure if someone (Andreas) will scream at me for that ^^. 
Another thing is the virtuelle Warteraum, if you already have that we could include it. Also development is bottlenecked by the process itself unless you already have the x_paths for the further buttons in the process lying around.

**Comment by cdaniel42** [comment]
Feature is available in branch, but maybe not quite pretty enough yet to PR. There is also an option for tabbed browsing which might increase the chances but steals focus.

**Comment by bastian987** [comment]
@cdaniel42 did you already test it and have actually been able to get a code?

**Comment by cdaniel42** [comment]
Yes, but in individual code call steps. Currently trying to make sure the
script would also run through as is.
 However, you still have to enter some personal information in the final
step to get the code, this part is not yet automated because I am
relatively sure that this step is not gated anymore.
Thinking about it, this does mean that the code should pause at that point
because reloading another site would reset the progress. This should not be
an issue when you use the tabbed browsing feature.
