### ISSUE TITLE
No buttons found

### ISSUE THREAD

**Issue by bastian987** [andreasdoerr/impf_termin_tester#18]
In almost all requests, the script seems to be redirected to the starting page (and, as a result, no appointments are found). Do you experience similar issues?

**Comment by tensau** [comment]
This usually happens if you're trapped in the rate limiting caused by too many requests in a given time. Probably it could help if the cookies are deleted before every request.

**Comment by bastian987** [comment]
Thanks @tensau! I tried that in the meantime, but without success: almost all (all?) requests seem to get redirected to the starting page. I used a random sleep interval of 5 to 10 minutes between requests for my test.

Any other ideas are welcome.

**Comment by bastian987** [comment]
Just tried it by setting a random user agent on startup of the script without success, get redirected to starting page on first run of the script.

**Comment by bastian987** [comment]
I assume the issue is the specific code, trying a different one now.

**Comment by bastian987** [comment]
new code seems to work, closing issue.
