### ISSUE TITLE
win32 dependency

### ISSUE THREAD

**Issue by ThomasWaldmann** [andreasdoerr/impf_termin_tester#7]
problems:

- the example.py code imports the outlook notifier module
- the outlook notifier imports pywin32
- pywin32 can't be installed on linux: "ERROR: Could not find a version that satisfies the requirement pywin32"
- environment.yml contains pywin32

this alltogether makes the code a bit problematic to use "as is" if one is not working on windows.

i worked around it by not using environment.yml (didn't use conda anyway, but just a normal virtualenv, installed all packages manually, except pywin32), commented the not working imports.

maybe this could get worked around somehow. alternatively, see my PR #2 which could either complement or replace the outlook based notifier.

**Comment by andreasdoerr** [comment]
Good point. I'd remove the windows specific parts from the general setup (`environment.yml` ) and add a section to the readme about this notification channel/option. In the example, I'd comment out the windows specific options.

**Comment by andreasdoerr** [comment]
Damn. shouldn't be allowed to directly push to master :D is there no option in the free github version to protect this branch?

Anyway... Issue should be fixed.

**Comment by ThomasWaldmann** [comment]
iirc there is a setting to disallow push to master.

otoh, if one always creates a feature branch before starting on something, there's usually no problem.
